version: "3.8"

services:
  postgres:
    image: postgres:13.8-bullseye
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.16-bullseye
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data

  wine-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nmngo248/wine-api:latest
    container_name: wine-api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Paris
    volumes:
      - .:/app
      - ./db_data:/app/db_data
      - ./logs:/app/logs
      - ./model:/app/model
      - ./model_data:/app/model_data
    depends_on:
      - postgres
      - redis

networks:
  default:
    name: wine-network