# Generated by Django 3.2.22 on 2024-01-14 11:01

from django.db import migrations, models
import winery.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, serialize=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, serialize=True)),
                ('winery_id', models.IntegerField(db_column='WineryID', null=True)),
                ('winery_name', models.CharField(db_column='WineryName', max_length=255, serialize=True)),
                ('website', models.CharField(db_column='Website', max_length=255, serialize=True)),
            ],
            options={
                'db_table': 'winery',
                'ordering': ['id'],
            },
            managers=[
                ('objects', winery.managers.WineryManager()),
            ],
        ),
    ]
