# Generated by Django 3.2.22 on 2024-01-14 11:01

from django.db import migrations, models
import django.db.models.deletion
import wine.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('winery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, serialize=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, serialize=True)),
                ('wine_id', models.IntegerField(db_column='WineID', editable=False, unique=True, serialize=True)),
                ('wine_name', models.CharField(db_column='WineName', max_length=255, serialize=True)),
                ('type', models.CharField(db_column='Type', max_length=255, serialize=True)),
                ('elaborate', models.CharField(db_column='Elaborate', max_length=255, serialize=True)),
                ('abv', models.FloatField(db_column='ABV', serialize=True)),
                ('body', models.CharField(db_column='Body', max_length=255, serialize=True)),
                ('acidity', models.CharField(db_column='Acidity', max_length=255, serialize=True)),
                ('region', models.ForeignKey(db_column='RegionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region', serialize=True)),
                ('winery', models.ForeignKey(db_column='WineryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='winery.winery', serialize=True)),
            ],
            options={
                'db_table': 'wine',
                'ordering': ['id'],
            },
            managers=[
                ('objects', wine.managers.WineManager()),
            ],
        ),
    ]
